### ISSUE TITLE
Add current release to Downloads page

### ISSUE THREAD

**Issue by jasonkarns** [sinonjs/sinon-docs#12]
It took me by complete surprise that the current release isn't on the downloads page at all. It called into question what the server/ie releases were.

**Comment by cjohansen** [comment]
1.14.1 is the current release, and it's on the downloads page.

**Comment by jasonkarns** [comment]
I beg to differ. Only the xhr and timers standalone builds are current.

![image](https://cloud.githubusercontent.com/assets/119972/7210108/e6108f82-e51c-11e4-9a2b-8eaf3c5b1028.png)

**Comment by cjohansen** [comment]
Hmm, guess you're right. You can grab it from the frontpage ;)

**Comment by jasonkarns** [comment]
I know I can. But that's not obvious from the downloads page. That's
precisely what's confusing. I spent about 5 minutes attempting to do the
PR, but I'm not familiar with this site's generator.

**Comment by cjohansen** [comment]
There was a bug - the download page had the download button placeholder, but not the code that replace it with the button. Fixed now.
