### ISSUE TITLE
Errors in README concerning midje

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon-docs#14]
When I created a PR recently I really tried doing "the right thing" by following the docs instructions, so I forked the project, cloned it, changed what was needed, and then tried running the tests. But that part did not work. I just get a `'midje' is not a task. See 'lein help'.` 

So I am guessing there is a step in the README missing on how to install `midje`, but as I built the site and visually inspected that the fix was working, I am not looking into that, as Clojure infrastructure is not my forte.

**Comment by magnars** [comment]
Looks like it should be 
```lein with-profile +test midje
```

**Comment by cjohansen** [comment]
https://github.com/sinonjs/sinon-docs/commit/64ae73732910092ffb039b11c7919ea847680a22

**Comment by cjohansen** [comment]
Thanks!
